export const CREATE_FILM_REQUEST = "CREATE_FILM_REQUEST";
export const CREATE_FILM_SUCCESS = "CREATE_FILM_SUCCESS";
export const CREATE_FILM_FAILURE = "CREATE_FILM_FAILURE";

export const UPDATE_FILM_REQUEST = "UPDATE_FILM_REQUEST";
export const UPDATE_FILM_SUCCESS = "UPDATE_FILM_SUCCESS";
export const UPDATE_FILM_FAILURE = "UPDATE_FILM_FAILURE";

export const DELETE_FILM_REQUEST = "DELETE_FILM_REQUEST";
export const DELETE_FILM_SUCCESS = "DELETE_FILM_SUCCESS";
export const DELETE_FILM_FAILURE = "DELETE_FILM_FAILURE";

export const GET_ALL_FILMS_REQUEST = "GET_ALL_FILMS_REQUEST";
export const GET_ALL_FILMS_SUCCESS = "GET_ALL_FILMS_SUCCESS";
export const GET_ALL_FILMS_FAILURE = "GET_ALL_FILMS_FAILURE";

export const SET_SELECTED_FILM = "SET_SELECTED_FILM";
export const SET_CURRENT_FILM_NUMBER = "SET_CURRENT_FILM_NUMBER";