export const CREATE_SNACK_REQUEST = "CREATE_SNACK_REQUEST";
export const CREATE_SNACK_SUCCESS = "CREATE_SNACK_SUCCESS";
export const CREATE_SNACK_FAILURE = "CREATE_SNACK_FAILURE";

export const GET_SNACK_LIST_REQUEST = "GET_SNACK_LIST_REQUEST";
export const GET_SNACK_LIST_SUCCESS = "GET_SNACK_LIST_SUCCESS";
export const GET_SNACK_LIST_FAILURE = "GET_SNACK_LIST_FAILURE";

export const DELETE_SNACK_REQUEST = "DELETE_SNACK_REQUEST";
export const DELETE_SNACK_SUCCESS = "DELETE_SNACK_SUCCESS";
export const DELETE_SNACK_FAILURE = "DELETE_SNACK_FAILURE";

export const UPDATE_SNACK_REQUEST = "UPDATE_SNACK_REQUEST";
export const UPDATE_SNACK_SUCCESS = "UPDATE_SNACK_SUCCESS";
export const UPDATE_SNACK_FAILURE = "UPDATE_SNACK_FAILURE";

export const BUY_SNACK_REQUEST = "BUY_SNACK_REQUEST";
export const BUY_SNACK_SUCCESS = "BUY_SNACK_SUCCESS";
export const BUY_SNACK_FAILURE = "BUY_SNACK_FAILURE";