export const SEND_REVIEW_REQUEST = "SEND_REVIEW_REQUEST";
export const SEND_REVIEW_SUCCESS = "SEND_REVIEW_SUCCESS";
export const SEND_REVIEW_FAILURE = "SEND_REVIEW_FAILURE";

export const GET_REVIEWS_BY_FILM_ID_REQUEST = "GET_REVIEWS_BY_FILM_ID_REQUEST";
export const GET_REVIEWS_BY_FILM_ID_SUCCESS = "GET_REVIEWS_BY_FILM_ID_SUCCESS";
export const GET_REVIEWS_BY_FILM_ID_FAILURE = "GET_REVIEWS_BY_FILM_ID_FAILURE";

export const DELETE_REVIEW_REQUEST = "DELETE_REVIEW_REQUEST";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_FAILURE = "DELETE_REVIEW_FAILURE";

export const GET_ALL_REVIEWS_REQUEST = "GET_ALL_REVIEWS_REQUEST";
export const GET_ALL_REVIEWS_SUCCESS = "GET_ALL_REVIEWS_SUCCESS";
export const GET_ALL_REVIEWS_FAILURE = "GET_ALL_REVIEWS_FAILURE";