export const VIEW_USER_TICKETS_REQUEST = "VIEW_USER_TICKETS_REQUEST";
export const VIEW_USER_TICKETS_SUCCESS = "VIEW_USER_TICKETS_SUCCESS";
export const VIEW_USER_TICKETS_FAILURE = "VIEW_USER_TICKETS_FAILURE";

export const GET_USER_TICKETS_REQUEST = "GET_USER_TICKETS_REQUEST";
export const GET_USER_TICKETS_SUCCESS = "GET_USER_TICKETS_SUCCESS";
export const GET_USER_TICKETS_FAILURE = "GET_USER_TICKETS_FAILURE";

export const GET_TICKETS_BY_HALL_ID_REQUEST = "GET_TICKETS_BY_HALL_ID_REQUEST";
export const GET_TICKETS_BY_HALL_ID_SUCCESS = "GET_TICKETS_BY_HALL_ID_SUCCESS";
export const GET_TICKETS_BY_HALL_ID_FAILURE = "GET_TICKETS_BY_HALL_ID_FAILURE";

export const BOOK_TICKET_REQUEST = "BOOK_TICKET_REQUEST";
export const BOOK_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS";
export const BOOK_TICKET_FAILURE = "BOOK_TICKET_FAILURE";

export const BUY_TICKET_REQUEST = "BOOK_TICKET_REQUEST";
export const BUY_TICKET_SUCCESS = "BOOK_TICKET_SUCCESS";
export const BUY_TICKET_FAILURE = "BOOK_TICKET_FAILURE";

export const CANCEL_TICKET_REQUEST = "CANCEL_TICKET_REQUEST";
export const CANCEL_TICKET_SUCCESS = "CANCEL_TICKET_SUCCESS";
export const CANCEL_TICKET_FAILURE = "CANCEL_TICKET_FAILURE";