export const CREATE_SALE_REQUEST = "CREATE_SALE_REQUEST";
export const CREATE_SALE_SUCCESS = "CREATE_SALE_SUCCESS";
export const CREATE_SALE_FAILURE = "CREATE_SALE_FAILURE";

export const GET_SALE_LIST_REQUEST = "GET_SALE_LIST_REQUEST";
export const GET_SALE_LIST_SUCCESS = "GET_SALE_LIST_SUCCESS";
export const GET_SALE_LIST_FAILURE = "GET_SALE_LIST_FAILURE";

export const UPDATE_SALE_REQUEST = "UPDATE_SALE_REQUEST";
export const UPDATE_SALE_SUCCESS = "UPDATE_SALE_SUCCESS";
export const UPDATE_SALE_FAILURE = "UPDATE_SALE_FAILURE";

export const DELETE_SALE_REQUEST = "DELETE_SALE_REQUEST";
export const DELETE_SALE_SUCCESS = "DELETE_SALE_SUCCESS";
export const DELETE_SALE_FAILURE = "DELETE_SALE_FAILURE";

export const APPLY_SALE_REQUEST = "APPLY_SALE_REQUEST";
export const APPLY_SALE_SUCCESS = "APPLY_SALE_SUCCESS";
export const APPLY_SALE_FAILURE = "APPLY_SALE_FAILURE";

export const GET_TOTAL_AMOUNT = "GET_TOTAL_AMOUNT";