export const GET_ALL_LOCATIONS_REQUEST = "GET_ALL_LOCATIONS_REQUEST";
export const GET_ALL_LOCATIONS_SUCCESS = "GET_ALL_LOCATIONS_SUCCESS";
export const GET_ALL_LOCATIONS_FAILURE = "GET_ALL_LOCATIONS_FAILURE";

export const SET_SELECTED_LOCATION = "SET_SELECTED_LOCATION";