export const CREATE_HALL_REQUEST = "CREATE_HALL_REQUEST";
export const CREATE_HALL_SUCCESS = "CREATE_HALL_SUCCESS";
export const CREATE_HALL_FAILURE = "CREATE_HALL_FAILURE";

export const UPDATE_HALL_REQUEST = "UPDATE_HALL_REQUEST";
export const UPDATE_HALL_SUCCESS = "UPDATE_HALL_SUCCESS";
export const UPDATE_HALL_FAILURE = "UPDATE_HALL_FAILURE";

export const DELETE_HALL_REQUEST = "DELETE_HALL_REQUEST";
export const DELETE_HALL_SUCCESS = "DELETE_HALL_SUCCESS";
export const DELETE_HALL_FAILURE = "DELETE_HALL_FAILURE";

export const GET_HALL_REQUEST = "GET_HALL_REQUEST";
export const GET_HALL_SUCCESS = "GET_HALL_SUCCESS";
export const GET_HALL_FAILURE = "GET_HALL_FAILURE";

export const GET_ALL_HALLS_REQUEST = "GET_ALL_HALLS_REQUEST";
export const GET_ALL_HALLS_SUCCESS = "GET_ALL_HALLS_SUCCESS";
export const GET_ALL_HALLS_FAILURE = "GET_ALL_HALLS_FAILURE";

export const OPEN_HALL_REQUEST = "OPEN_HALL_REQUEST";
export const OPEN_HALL_SUCCESS = "OPEN_HALL_SUCCESS";
export const OPEN_HALL_FAILURE = "OPEN_HALL_FAILURE";

export const CLOSE_HALL_REQUEST = "CLOSE_HALL_REQUEST";
export const CLOSE_HALL_SUCCESS = "CLOSE_HALL_SUCCESS";
export const CLOSE_HALL_FAILURE = "CLOSE_HALL_FAILURE";

export const SET_SELECTED_HALL = "SET_SELECTED_HALL";