export const UPDATE_USER_PROFILE_REQUEST = "UPDATE_USER_PROFILE_REQUEST";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE_FAILURE = "UPDATE_USER_PROFILE_FAILURE";

export const GET_USER_LIST_REQUEST = "GET_USER_LIST_REQUEST";
export const GET_USER_LIST_SUCCESS = "GET_USER_LIST_SUCCESS";
export const GET_USER_LIST_FAILURE = "GET_USER_LIST_FAILURE";

export const BLOCK_USER_REQUEST = "BLOCK_USER_REQUEST";
export const BLOCK_USER_SUCCESS = "BLOCK_USER_SUCCESS";
export const BLOCK_USER_FAILURE = "BLOCK_USER_FAILURE";

export const FILTER_FILMS_REQUEST = "FILTER_FILMS_REQUEST";
export const FILTER_FILMS_SUCCESS = "FILTER_FILMS_SUCCESS";
export const FILTER_FILMS_FAILURE = "FILTER_FILMS_FAILURE";

export const SEARCH_FILMS_REQUEST = "SEARCH_FILMS_REQUEST";
export const SEARCH_FILMS_SUCCESS = "SEARCH_FILMS_SUCCESS";
export const SEARCH_FILMS_FAILURE = "SEARCH_FILMS_FAILURE";

export const SET_FILTERS = "SET_FILTERS";